Repository Status-Plus/Status-Plus-Translation, pull requests merged in 2022-01, with the labels that each got.

#1 Spanish translations
  languages/ES.json
Labels: good first issue, awaiting verification

#2 Create PH.json
  languages/TL.json
Labels: awaiting verification

#4 Provided Chinese Translations
  languages/ZHCN.json
Labels: awaiting verification

#5 Portuguese Brazil Translations
  languages/PT_BR.json
Labels: awaiting verification

#9 Indonesian translation
  languages/ID.json
Labels: help wanted, awaiting verification

#17 Update Chinese translation
  languages/ZH.json
Labels: awaiting verification
